from tilestache_cache_provider import make_tilestache_filesystem_cache
from tilestache_cache_provider import make_tilestache_s3_cache

__all__ = [make_tilestache_filesystem_cache, make_tilestache_s3_cache]
